In the match data generated in data_generation.ipynb, player1 is always the winner. For the purpose of future data exploration and modeling, we exchange player1 and player2 for half of the matches and save it in another csv file.

In [1]:
import pandas as pd
import numpy as np
import random

In [2]:
data = pd.read_csv('match_data_50_tourns.csv')

In [3]:
data.head()

,player1,player2,best_of,player1_elo,player2_elo,elo_match_win_rate,elo_frame_win_rate,p1_matches_played,p1_matches_won,p1_frames_played,...,p1_frames_won_3_years,p2_frames_played_1_year,p2_frames_won_1_year,p2_frames_played_3_years,p2_frames_won_3_years,score1,score2,match_result,win_percentage,tournament_id
0,Cao Yupeng,Jiang Jun,9,1411,1044,0.918016,0.714532,341,179,2302,...,242,32,17,32,17,5,0,0.0,1.000000,5808
1,Zhou Yuelong,Siripaporn Nuanthakhamjan,9,1384,965,0.943119,0.740295,459,272,2879,...,430,23,4,23,4,5,2,0.0,0.714286,5808
2,Wu Yize,Allan Taylor,9,1342,1237,0.656987,0.565251,78,37,552,...,215,101,49,336,147,5,3,0.0,0.625000,5808
3,Ben Woollaston,Oliver Brown,9,1412,1146,0.845318,0.660383,803,454,5053,...,282,91,35,235,97,5,2,0.0,0.714286,5808
4,Mark Williams,Andres Petrov,9,1611,1045,0.982235,0.804553,1751,1151,12775,...,649,79,25,167,61,5,2,0.0,0.714286,5808

In [4]:
row = data.loc[0]

In [5]:
#We use random.shuffle to choose the indices of matches we want to modify.
match_index = list(range(len(data)))
random.shuffle(match_index)
modify_index = match_index[:len(data)//2]

In [6]:
modify_index[:5]

[2909, 2144, 844, 3967, 4733]

In [7]:
data.loc[modify_index].head(5)

,player1,player2,best_of,player1_elo,player2_elo,elo_match_win_rate,elo_frame_win_rate,p1_matches_played,p1_matches_won,p1_frames_played,...,p1_frames_won_3_years,p2_frames_played_1_year,p2_frames_won_1_year,p2_frames_played_3_years,p2_frames_won_3_years,score1,score2,match_result,win_percentage,tournament_id
2909,Farakh Ajaib,Haitham Al Mahri,7,1153,1000,0.699444,0.594476,153,66,832,...,136,0,0,0,0,4,0,0.0,1.000000,6265
2144,Muhammad Umar Khan,Mohammad Reza Pishvari,7,993,999,0.491797,0.496250,1,0,6,...,2,12,6,12,6,4,1,0.0,0.800000,6183
844,Oliver Lines,Ma Hailong,1,1355,1077,0.667078,0.667078,358,171,2160,...,263,134,55,134,55,1,0,0.0,1.000000,5875
3967,Ding Junhui,Jiang Jun,9,1541,1266,0.853217,0.665411,1020,678,7848,...,420,20,12,348,170,5,1,0.0,0.833333,6445
4733,Zhao Hanyang,Thor Chuan Leong,7,991,1243,0.195762,0.347511,10,4,54,...,14,74,37,375,185,4,3,0.0,0.571429,6786

In [8]:
#Create a new dataframe df to store the modified data
df = data.loc[modify_index]

In [9]:
data.columns

Index(['player1', 'player2', 'best_of', 'player1_elo', 'player2_elo',
       'elo_match_win_rate', 'elo_frame_win_rate', 'p1_matches_played',
       'p1_matches_won', 'p1_frames_played', 'p1_frames_won',
       'p2_matches_played', 'p2_matches_won', 'p2_frames_played',
       'p2_frames_won', 'p1_frames_played_1_year', 'p1_frames_won_1_year',
       'p1_frames_played_3_years', 'p1_frames_won_3_years',
       'p2_frames_played_1_year', 'p2_frames_won_1_year',
       'p2_frames_played_3_years', 'p2_frames_won_3_years', 'score1', 'score2',
       'match_result', 'win_percentage', 'tournament_id'],
      dtype='object')

In [10]:
#Exchange the stats of player1 and player2
df['player1'], df['player2'] = df['player2'], df['player1']
df['player1_elo'], df['player2_elo'] = df['player2_elo'], df['player1_elo']
df['elo_match_win_rate'], df['elo_frame_win_rate'] = 1-df['elo_match_win_rate'], 1-df['elo_frame_win_rate']
df['p1_matches_played'], df['p1_matches_won'], df['p2_matches_played'], df['p2_matches_won'] = df['p2_matches_played'], df['p2_matches_won'], df['p1_matches_played'], df['p1_matches_won']
df['p1_frames_played'], df['p1_frames_won'], df['p2_frames_played'], df['p2_frames_won'] = df['p2_frames_played'], df['p2_frames_won'], df['p1_frames_played'], df['p1_frames_won']
df['p1_frames_played_1_year'], df['p1_frames_won_1_year'], df['p2_frames_played_1_year'], df['p2_frames_won_1_year'] = df['p2_frames_played_1_year'], df['p2_frames_won_1_year'], df['p1_frames_played_1_year'], df['p1_frames_won_1_year']
df['p1_frames_played_3_years'], df['p1_frames_won_3_years'], df['p2_frames_played_3_years'], df['p2_frames_won_3_years'] = df['p2_frames_played_3_years'], df['p2_frames_won_3_years'], df['p1_frames_played_3_years'], df['p1_frames_won_3_years']
df['score1'], df['score2'] = df['score2'], df['score1']
df['match_result'] = 1
df['win_percentage'] = 1 - df['win_percentage']

In [11]:
data.loc[modify_index] = df

In [12]:
data.head()

,player1,player2,best_of,player1_elo,player2_elo,elo_match_win_rate,elo_frame_win_rate,p1_matches_played,p1_matches_won,p1_frames_played,...,p1_frames_won_3_years,p2_frames_played_1_year,p2_frames_won_1_year,p2_frames_played_3_years,p2_frames_won_3_years,score1,score2,match_result,win_percentage,tournament_id
0,Cao Yupeng,Jiang Jun,9,1411,1044,0.918016,0.714532,341,179,2302,...,242,32,17,32,17,5,0,0.0,1.000000,5808
1,Siripaporn Nuanthakhamjan,Zhou Yuelong,9,965,1384,0.056881,0.259705,3,0,23,...,4,245,118,808,430,2,5,1.0,0.285714,5808
2,Wu Yize,Allan Taylor,9,1342,1237,0.656987,0.565251,78,37,552,...,215,101,49,336,147,5,3,0.0,0.625000,5808
3,Ben Woollaston,Oliver Brown,9,1412,1146,0.845318,0.660383,803,454,5053,...,282,91,35,235,97,5,2,0.0,0.714286,5808
4,Andres Petrov,Mark Williams,9,1045,1611,0.017765,0.195447,51,18,304,...,61,281,170,1112,649,2,5,1.0,0.285714,5808

In [13]:
data.loc[modify_index].head(5)

,player1,player2,best_of,player1_elo,player2_elo,elo_match_win_rate,elo_frame_win_rate,p1_matches_played,p1_matches_won,p1_frames_played,...,p1_frames_won_3_years,p2_frames_played_1_year,p2_frames_won_1_year,p2_frames_played_3_years,p2_frames_won_3_years,score1,score2,match_result,win_percentage,tournament_id
2909,Haitham Al Mahri,Farakh Ajaib,7,1000,1153,0.300556,0.405524,0,0,0,...,0,74,43,280,136,0,4,1.0,0.000000,6265
2144,Mohammad Reza Pishvari,Muhammad Umar Khan,7,999,993,0.508203,0.503750,2,1,12,...,6,6,2,6,2,1,4,1.0,0.200000,6183
844,Ma Hailong,Oliver Lines,1,1077,1355,0.332922,0.332922,20,6,134,...,55,222,116,520,263,0,1,1.0,0.000000,5875
3967,Jiang Jun,Ding Junhui,9,1266,1541,0.146783,0.334589,50,22,348,...,170,0,0,762,420,1,5,1.0,0.166667,6445
4733,Thor Chuan Leong,Zhao Hanyang,7,1243,991,0.804238,0.652489,208,78,1318,...,185,15,10,27,14,3,4,1.0,0.428571,6786

In [14]:
data.to_csv('match_data_50_tourns_modified.csv', index=False)