In the match data generated in data_generation.ipynb, player1 is always the winner. For the purpose of future data exploration and modeling, we exchange player1 and player2 for half of the matches and save it in another csv file.

In [1]:
import pandas as pd
import numpy as np
import random

In [2]:
data = pd.read_csv('match_data_20_tourns.csv')

In [3]:
data.head()

,player1,player2,best_of,player1_elo,player2_elo,elo_match_win_rate,elo_frame_win_rate,p1_matches_played,p1_matches_won,p1_frames_played,...,p1_frames_played_3_years,p1_frames_won_3_years,p2_frames_played_1_year,p2_frames_won_1_year,p2_frames_played_3_years,p2_frames_won_3_years,score1,score2,match_result,win_percentage
0,Long Zehuang,Haydon Pinhey,7,1328,1158,0.719210,0.604679,78,39,443,...,284,147,121,57,347,168,4,3,0.0,0.571429
1,Wang Yuchen,Andrew Pagett,7,1162,1162,0.500000,0.500000,100,37,626,...,158,89,144,65,417,170,4,1,0.0,0.800000
2,Daniel Womersley,Ben Mertens,7,1109,1262,0.300556,0.405524,109,53,551,...,180,89,136,67,471,240,4,1,0.0,0.800000
3,Jimmy White,Paul Deaville,7,1141,1096,0.561265,0.528095,1577,844,13093,...,384,153,97,51,126,66,4,3,0.0,0.571429
4,Alexander Ursenbacher,Mostafa Dorgham,7,1302,1031,0.821305,0.663180,286,129,1728,...,400,196,108,41,154,53,4,1,0.0,0.800000

In [4]:
row = data.loc[0]

In [5]:
#We use random.shuffle to choose the indices of matches we want to modify.
match_index = list(range(len(data)))
random.shuffle(match_index)
modify_index = match_index[:len(data)//2]

In [6]:
modify_index[:5]

[523, 1570, 154, 1038, 400]

In [7]:
data.loc[modify_index].head(5)

,player1,player2,best_of,player1_elo,player2_elo,elo_match_win_rate,elo_frame_win_rate,p1_matches_played,p1_matches_won,p1_frames_played,...,p1_frames_played_3_years,p1_frames_won_3_years,p2_frames_played_1_year,p2_frames_won_1_year,p2_frames_played_3_years,p2_frames_won_3_years,score1,score2,match_result,win_percentage
523,Judd Trump,Kyren Wilson,11,1649,1620,0.548936,0.518117,1484,1069,10282,...,1844,1132,681,399,1573,923,6,2,0.0,0.750000
1570,Babar Masih,Tian Pengfei,7,1003,1232,0.217783,0.360660,12,3,80,...,42,20,49,20,441,213,4,0,0.0,1.000000
154,Shaun Murphy,Louis Heathcote,11,1536,1306,0.833719,0.639916,1380,907,9959,...,999,570,203,105,551,270,6,4,0.0,0.600000
1038,Jack Lisowski,Jak Jones,5,1442,1462,0.476577,0.487503,828,505,5422,...,817,451,29,18,773,427,3,1,0.0,0.750000
400,Robbie Mcguigan,Habib Subah Humood,11,1057,966,0.650074,0.556631,75,26,359,...,223,95,5,1,14,2,6,3,0.0,0.666667

In [8]:
#Create a new dataframe df to store the modified data
df = data.loc[modify_index]

In [9]:
data.columns

Index(['player1', 'player2', 'best_of', 'player1_elo', 'player2_elo',
       'elo_match_win_rate', 'elo_frame_win_rate', 'p1_matches_played',
       'p1_matches_won', 'p1_frames_played', 'p1_frames_won',
       'p2_matches_played', 'p2_matches_won', 'p2_frames_played',
       'p2_frames_won', 'p1_frames_played_1_year', 'p1_frames_won_1_year',
       'p1_frames_played_3_years', 'p1_frames_won_3_years',
       'p2_frames_played_1_year', 'p2_frames_won_1_year',
       'p2_frames_played_3_years', 'p2_frames_won_3_years', 'score1', 'score2',
       'match_result', 'win_percentage'],
      dtype='object')

In [10]:
#Exchange the stats of player1 and player2
df['player1'], df['player2'] = df['player2'], df['player1']
df['player1_elo'], df['player2_elo'] = df['player2_elo'], df['player1_elo']
df['elo_match_win_rate'], df['elo_frame_win_rate'] = 1-df['elo_match_win_rate'], 1-df['elo_frame_win_rate']
df['p1_matches_played'], df['p1_matches_won'], df['p2_matches_played'], df['p2_matches_won'] = df['p2_matches_played'], df['p2_matches_won'], df['p1_matches_played'], df['p1_matches_won']
df['p1_frames_played'], df['p1_frames_won'], df['p2_frames_played'], df['p2_frames_won'] = df['p2_frames_played'], df['p2_frames_won'], df['p1_frames_played'], df['p1_frames_won']
df['p1_frames_played_1_year'], df['p1_frames_won_1_year'], df['p2_frames_played_1_year'], df['p2_frames_won_1_year'] = df['p2_frames_played_1_year'], df['p2_frames_won_1_year'], df['p1_frames_played_1_year'], df['p1_frames_won_1_year']
df['p1_frames_played_3_years'], df['p1_frames_won_3_years'], df['p2_frames_played_3_years'], df['p2_frames_won_3_years'] = df['p2_frames_played_3_years'], df['p2_frames_won_3_years'], df['p1_frames_played_3_years'], df['p1_frames_won_3_years']
df['score1'], df['score2'] = df['score2'], df['score1']
df['match_result'] = 1
df['win_percentage'] = 1 - df['win_percentage']

In [11]:
data.loc[modify_index] = df

In [12]:
data.head()

,player1,player2,best_of,player1_elo,player2_elo,elo_match_win_rate,elo_frame_win_rate,p1_matches_played,p1_matches_won,p1_frames_played,...,p1_frames_played_3_years,p1_frames_won_3_years,p2_frames_played_1_year,p2_frames_won_1_year,p2_frames_played_3_years,p2_frames_won_3_years,score1,score2,match_result,win_percentage
0,Long Zehuang,Haydon Pinhey,7,1328,1158,0.719210,0.604679,78,39,443,...,284,147,121,57,347,168,4,3,0.0,0.571429
1,Wang Yuchen,Andrew Pagett,7,1162,1162,0.500000,0.500000,100,37,626,...,158,89,144,65,417,170,4,1,0.0,0.800000
2,Ben Mertens,Daniel Womersley,7,1262,1109,0.699444,0.594476,107,50,642,...,471,240,86,40,180,89,1,4,1.0,0.200000
3,Paul Deaville,Jimmy White,7,1096,1141,0.438735,0.471905,32,17,158,...,126,66,85,31,384,153,3,4,1.0,0.428571
4,Alexander Ursenbacher,Mostafa Dorgham,7,1302,1031,0.821305,0.663180,286,129,1728,...,400,196,108,41,154,53,4,1,0.0,0.800000

In [13]:
data.loc[modify_index].head(5)

,player1,player2,best_of,player1_elo,player2_elo,elo_match_win_rate,elo_frame_win_rate,p1_matches_played,p1_matches_won,p1_frames_played,...,p1_frames_played_3_years,p1_frames_won_3_years,p2_frames_played_1_year,p2_frames_won_1_year,p2_frames_played_3_years,p2_frames_won_3_years,score1,score2,match_result,win_percentage
523,Kyren Wilson,Judd Trump,11,1620,1649,0.451064,0.481883,1078,690,6880,...,1573,923,623,392,1844,1132,2,6,1.0,0.250000
1570,Tian Pengfei,Babar Masih,7,1232,1003,0.782217,0.639340,583,316,3828,...,441,213,7,3,42,20,0,4,1.0,0.000000
154,Louis Heathcote,Shaun Murphy,11,1306,1536,0.166281,0.360084,211,99,1232,...,551,270,327,185,999,570,4,6,1.0,0.400000
1038,Jak Jones,Jack Lisowski,5,1462,1442,0.523423,0.512497,427,214,2816,...,773,427,32,17,817,451,1,3,1.0,0.250000
400,Habib Subah Humood,Robbie Mcguigan,11,966,1057,0.349926,0.443369,3,0,14,...,14,2,82,32,223,95,3,6,1.0,0.333333

In [15]:
data.to_csv('match_data_20_tourns_modified.csv', index=False)