In [1]:
import pandas as pd

In [2]:
data1 = pd.read_csv('/Users/tliu/Desktop/Erdos Project/3_Player_Data_Generation/match_data_785_835_tourns_modified.csv')
data2 = pd.read_csv('/Users/tliu/Desktop/Erdos Project/3_Player_Data_Generation/match_data_835_885_tourns_modified.csv')
data3 = pd.read_csv('/Users/tliu/Desktop/Erdos Project/3_Player_Data_Generation/match_data_885_935_tourns_modified.csv')
data4 = pd.read_csv('/Users/tliu/Desktop/Erdos Project/3_Player_Data_Generation/match_data_935_985_tourns_modeified.csv')
data5 = pd.read_csv('/Users/tliu/Desktop/Erdos Project/3_Player_Data_Generation/match_data_985_1035_tourns_modified.csv')
data6 = pd.read_csv('/Users/tliu/Desktop/Erdos Project/3_Player_Data_Generation/match_data_50_tourns_modified.csv')

In [3]:
print(len(data1))
print(len(data2))
print(len(data3))
print(len(data4))
print(len(data5))
print(len(data6))

6255
5794
5561
6261
5592
5058

In [4]:
data = pd.concat([data1, data2, data3, data4, data5, data6], axis = 0, ignore_index = True)
data.head()

,player1,player2,best_of,player1_elo,player2_elo,elo_match_win_rate,elo_frame_win_rate,p1_matches_played,p1_matches_won,p1_frames_played,...,p1_frames_won_3_years,p2_frames_played_1_year,p2_frames_won_1_year,p2_frames_played_3_years,p2_frames_won_3_years,score1,score2,match_result,win_percentage,tournament_id
0,Mark Allen,Ricky Walden,7,1580,1418,0.709992,0.599888,501,313,3345,...,596,45,25,1032,557,0,4,1.0,0.000000,1063
1,Stephen Maguire,Judd Trump,7,1563,1551,0.516401,0.507499,663,444,4995,...,739,122,79,1344,782,1,4,1.0,0.200000,1063
2,Mark Selby,Steve Davis,7,1592,1246,0.878716,0.703704,736,495,5330,...,875,8,2,581,286,4,1,0.0,0.800000,1063
3,Neil Robertson,Ali Carter,7,1546,1544,0.502734,0.501250,621,402,4581,...,815,11,5,876,499,4,0,0.0,1.000000,1063
4,Stuart Bingham,Ronnie O'Sullivan,7,1488,1663,0.275106,0.392337,744,462,5592,...,680,71,46,674,431,2,4,1.0,0.333333,1063

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34521 entries, 0 to 34520
Data columns (total 28 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   player1                   34521 non-null  object
 1   player2                   34521 non-null  object
 2   best_of                   34521 non-null  int64
 3   player1_elo               34521 non-null  int64
 4   player2_elo               34521 non-null  int64
 5   elo_match_win_rate        34521 non-null  float64
 6   elo_frame_win_rate        34521 non-null  float64
 7   p1_matches_played         34521 non-null  int64
 8   p1_matches_won            34521 non-null  int64
 9   p1_frames_played          34521 non-null  int64
 10  p1_frames_won             34521 non-null  int64
 11  p2_matches_played         34521 non-null  int64
 12  p2_matches_won            34521 non-null  int64
 13  p2_frames_played          34521 non-null  int64
 14  p2_frames_won             34521 non-null  int64
 15  p1_frames_played_1_year   34521 non-null  int64
 16  p1_frames_won_1_year      34521 non-null  int64
 17  p1_frames_played_3_years  34521 non-null  int64
 18  p1_frames_won_3_years     34521 non-null  int64
 19  p2_frames_played_1_year   34521 non-null  int64
 20  p2_frames_won_1_year      34521 non-null  int64
 21  p2_frames_played_3_years  34521 non-null  int64
 22  p2_frames_won_3_years     34521 non-null  int64
 23  score1                    34521 non-null  int64
 24  score2                    34521 non-null  int64
 25  match_result              34521 non-null  float64
 26  win_percentage            34521 non-null  float64
 27  tournament_id             34521 non-null  int64
dtypes: float64(4), int64(22), object(2)
memory usage: 7.4+ MB

In [6]:
def date_format(s):
       
    if isinstance(s, str):
        return pd.to_datetime(s[:10], format = '%Y-%m-%d')
        print(s) 
    else:
        return None

In [7]:
matches = pd.read_csv('/Users/tliu/Desktop/Erdos Project/1_Match_Data/matches.csv')
matches = matches[-len(data):]
dates = matches['date'].apply(date_format)
data['date'] = dates.values

In [8]:
data.head()

,player1,player2,best_of,player1_elo,player2_elo,elo_match_win_rate,elo_frame_win_rate,p1_matches_played,p1_matches_won,p1_frames_played,...,p2_frames_played_1_year,p2_frames_won_1_year,p2_frames_played_3_years,p2_frames_won_3_years,score1,score2,match_result,win_percentage,tournament_id,date
0,Mark Allen,Ricky Walden,7,1580,1418,0.709992,0.599888,501,313,3345,...,45,25,1032,557,0,4,1.0,0.000000,1063,2014-11-07
1,Stephen Maguire,Judd Trump,7,1563,1551,0.516401,0.507499,663,444,4995,...,122,79,1344,782,1,4,1.0,0.200000,1063,2014-11-04
2,Mark Selby,Steve Davis,7,1592,1246,0.878716,0.703704,736,495,5330,...,8,2,581,286,4,1,0.0,0.800000,1063,2014-11-04
3,Neil Robertson,Ali Carter,7,1546,1544,0.502734,0.501250,621,402,4581,...,11,5,876,499,4,0,0.0,1.000000,1063,2014-11-07
4,Stuart Bingham,Ronnie O'Sullivan,7,1488,1663,0.275106,0.392337,744,462,5592,...,71,46,674,431,2,4,1.0,0.333333,1063,2014-11-05

In [9]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34521 entries, 0 to 34520
Data columns (total 29 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   player1                   34521 non-null  object
 1   player2                   34521 non-null  object
 2   best_of                   34521 non-null  int64
 3   player1_elo               34521 non-null  int64
 4   player2_elo               34521 non-null  int64
 5   elo_match_win_rate        34521 non-null  float64
 6   elo_frame_win_rate        34521 non-null  float64
 7   p1_matches_played         34521 non-null  int64
 8   p1_matches_won            34521 non-null  int64
 9   p1_frames_played          34521 non-null  int64
 10  p1_frames_won             34521 non-null  int64
 11  p2_matches_played         34521 non-null  int64
 12  p2_matches_won            34521 non-null  int64
 13  p2_frames_played          34521 non-null  int64
 14  p2_frames_won             34521 non-null  int64
 15  p1_frames_played_1_year   34521 non-null  int64
 16  p1_frames_won_1_year      34521 non-null  int64
 17  p1_frames_played_3_years  34521 non-null  int64
 18  p1_frames_won_3_years     34521 non-null  int64
 19  p2_frames_played_1_year   34521 non-null  int64
 20  p2_frames_won_1_year      34521 non-null  int64
 21  p2_frames_played_3_years  34521 non-null  int64
 22  p2_frames_won_3_years     34521 non-null  int64
 23  score1                    34521 non-null  int64
 24  score2                    34521 non-null  int64
 25  match_result              34521 non-null  float64
 26  win_percentage            34521 non-null  float64
 27  tournament_id             34521 non-null  int64
 28  date                      32681 non-null  datetime64[ns]
dtypes: datetime64[ns](1), float64(4), int64(22), object(2)
memory usage: 7.6+ MB

In [10]:
from sklearn.impute import KNNImputer
knn = KNNImputer(n_neighbors=1)
df = knn.fit_transform(data[['date']])
data['date'] = df

In [11]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34521 entries, 0 to 34520
Data columns (total 29 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   player1                   34521 non-null  object
 1   player2                   34521 non-null  object
 2   best_of                   34521 non-null  int64
 3   player1_elo               34521 non-null  int64
 4   player2_elo               34521 non-null  int64
 5   elo_match_win_rate        34521 non-null  float64
 6   elo_frame_win_rate        34521 non-null  float64
 7   p1_matches_played         34521 non-null  int64
 8   p1_matches_won            34521 non-null  int64
 9   p1_frames_played          34521 non-null  int64
 10  p1_frames_won             34521 non-null  int64
 11  p2_matches_played         34521 non-null  int64
 12  p2_matches_won            34521 non-null  int64
 13  p2_frames_played          34521 non-null  int64
 14  p2_frames_won             34521 non-null  int64
 15  p1_frames_played_1_year   34521 non-null  int64
 16  p1_frames_won_1_year      34521 non-null  int64
 17  p1_frames_played_3_years  34521 non-null  int64
 18  p1_frames_won_3_years     34521 non-null  int64
 19  p2_frames_played_1_year   34521 non-null  int64
 20  p2_frames_won_1_year      34521 non-null  int64
 21  p2_frames_played_3_years  34521 non-null  int64
 22  p2_frames_won_3_years     34521 non-null  int64
 23  score1                    34521 non-null  int64
 24  score2                    34521 non-null  int64
 25  match_result              34521 non-null  float64
 26  win_percentage            34521 non-null  float64
 27  tournament_id             34521 non-null  int64
 28  date                      34521 non-null  float64
dtypes: float64(5), int64(22), object(2)
memory usage: 7.6+ MB

In [12]:
data.to_csv('match_data_300_tourns_modified.csv', index = False)